In [ ]:
import numpy as np

a = np.array(['1.2', '2.5', '3.6', '4.8'])

In [ ]:
a

array(['1.2', '2.5', '3.6', '4.8'], dtype='<U3')

In [ ]:
#inside a numpy array, i have string elements

In [ ]:
#convert into a float

a= a.astype(float)

In [ ]:
a

array([1.2, 2.5, 3.6, 4.8])

In [ ]:
#customer_ids with auto increment of 1
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#customer_ids with auto increment of 2

x= np.arange(1,101,2)

In [ ]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
print(x[2])

5


In [ ]:
x[2]

np.int64(5)

In [ ]:
#stort way to add a stepper
print(x[::3])

[ 1  7 13 19 25 31 37 43 49 55 61 67 73 79 85 91 97]


In [ ]:
#short way to reverse
print(x[::-1])

[99 97 95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53
 51 49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5
  3  1]


In [ ]:
print(x[::-3])

[99 93 87 81 75 69 63 57 51 45 39 33 27 21 15  9  3]


In [ ]:
arr= np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr[::-2]

array([9, 7, 5, 3, 1])

In [ ]:
a = np.array([1, 2, 3, 4,12,'15'])


In [ ]:
a

array(['1.2', '2.5', '3.6', '4.8', '12', '15'], dtype='<U21')

In [ ]:
#Zomato --> Votes
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes>500

array([ True,  True,  True, False, False, False,  True, False,  True,
       False])

In [ ]:
#I only want the restaurants that have more than 500 votes

votes[votes>500] #filtering


array([ 775,  787,  918, 2556,  504])

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes[2]

np.int64(918)

In [ ]:
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
restaurants = np.array (["A", "B","C","D","E","F","G","H","I","J"])

In [ ]:
#FETCH NAMES OF THE RESTAURANTS WHO GOT THE VOTINGS >500

votes>500

array([ True,  True,  True, False, False, False,  True, False,  True,
       False])

In [ ]:
restaurants[votes>500] #gives actual values where the index is true


array(['A', 'B', 'C', 'G', 'I'], dtype='<U1')

In [ ]:
# 2D Arrays - is there an inbuilt way of creating 2D arrays

restaurants_data= np.column_stack((votes,restaurants))


In [ ]:
restaurants_data

array([['775', 'A'],
       ['787', 'B'],
       ['918', 'C'],
       ['88', 'D'],
       ['166', 'E'],
       ['286', 'F'],
       ['2556', 'G'],
       ['324', 'H'],
       ['504', 'I'],
       ['402', 'J']], dtype='<U21')

In [ ]:
restaurants_data.shape

(10, 2)

In [ ]:
restaurants_data.ndim

2

In [ ]:
#is there a way to change the shape

restaurants_data.reshape(3,3)

ValueError: cannot reshape array of size 20 into shape (3,3)

In [ ]:
restaurants_data.reshape(5,4)

array([['775', 'A', '787', 'B'],
       ['918', 'C', '88', 'D'],
       ['166', 'E', '286', 'F'],
       ['2556', 'G', '324', 'H'],
       ['504', 'I', '402', 'J']], dtype='<U21')

In [ ]:
reshaped_rest= restaurants_data.reshape(2,-1) #if you dont know what the shape could be, you can add an unknown dimension

print(reshaped_rest)

[['775' 'A' '787' 'B' '918' 'C' '88' 'D' '166' 'E']
 ['286' 'F' '2556' 'G' '324' 'H' '504' 'I' '402' 'J']]


In [ ]:
reshaped_rest.shape

(2, 10)

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
print(np.sum(votes))

6806


In [ ]:
print(np.mean(votes))

680.6


In [ ]:
print(np.min(votes))

88


In [ ]:
print(np.max(votes))

2556


In [ ]:
np.median(votes)

np.float64(453.0)

In [ ]:
x= np.arange(1,61,2)

In [ ]:
x.shape

(30,)

In [ ]:
y= x.reshape(15,2)
print(y)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]
 [33 35]
 [37 39]
 [41 43]
 [45 47]
 [49 51]
 [53 55]
 [57 59]]


In [ ]:
np.sum(y)

np.int64(900)

In [ ]:
np.sum(y, axis=0) #axis =0 row wise addition #axis=0 means add all the rows in each column

array([435, 465])

In [ ]:
np.sum(y, axis=1) #axis =1 column wise addition #axis=1 means add all the columns in each row

array([  4,  12,  20,  28,  36,  44,  52,  60,  68,  76,  84,  92, 100,
       108, 116])

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
np.sort(votes)

array([  88,  166,  286,  324,  402,  504,  775,  787,  918, 2556])

In [ ]:
x= np.sort(votes)[::-1]

array([2556,  918,  787,  775,  504,  402,  324,  286,  166,   88])

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
np.argsort(votes)

array([3, 4, 5, 7, 9, 8, 0, 1, 2, 6])

In [ ]:
#doubts

In [ ]:
np.column_stack((votes,restaurants))

array([['775', 'A'],
       ['787', 'B'],
       ['918', 'C'],
       ['88', 'D'],
       ['166', 'E'],
       ['286', 'F'],
       ['2556', 'G'],
       ['324', 'H'],
       ['504', 'I'],
       ['402', 'J']], dtype='<U21')

In [ ]:
np.column_stack([votes,restaurants])

array([['775', 'A'],
       ['787', 'B'],
       ['918', 'C'],
       ['88', 'D'],
       ['166', 'E'],
       ['286', 'F'],
       ['2556', 'G'],
       ['324', 'H'],
       ['504', 'I'],
       ['402', 'J']], dtype='<U21')

In [ ]:

import numpy as np
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
costs = np.array([800.0 ,800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0 ,550.0, 500.0])

In [ ]:
votes[votes>500]

array([ 775,  787,  918, 2556,  504])

In [ ]:
#more optional ways

#Check if at least one restaurant meets a condition (np.any()).

print(np.any(votes>500))

True


In [ ]:

np.all(votes>500)

np.False_

In [ ]:
###### Logical operations
costs = np.array([800.0 ,800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0 ,550.0, 500.0])
#Restaurants having cost for 2 > 500, "Expensive", "Economical"



In [ ]:
np.where(costs>500,"Expensive","Eco")

array(['Expensive', 'Expensive', 'Expensive', 'Eco', 'Expensive',
       'Expensive', 'Expensive', 'Expensive', 'Expensive', 'Eco'],
      dtype='<U9')

In [ ]:
#Multiplication in numpy

costs

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
costs * votes

array([ 620000.,  629600.,  734400.,   26400.,   99600.,  171600.,
       1533600.,  226800.,  277200.,  201000.])

In [ ]:
votes * 5

array([ 3875,  3935,  4590,   440,   830,  1430, 12780,  1620,  2520,
        2010])

In [ ]:
votes

demo = np.array([1,2,4,5])

In [ ]:
votes * demo

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [ ]:
#matrix multiplication

m1= np.arange(11,20).reshape(3,3)

In [ ]:
m2= np.arange(1,10).reshape(3,3)

In [ ]:
m1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1 * m2 #element wise

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [ ]:
#matrix multiplication
m1 @ m2

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
np.matmul(m1,m2)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
np.dot(m1,m2)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
array2d = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2d * 10 #concept- Broadcasting

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])


In [ ]:
array1 + array2

array([5, 7, 9])

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

array_1d = np.array([10, 20, 30])

In [ ]:
array_2d + array_1d

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

array_1d = np.array([10, 20])

array_2d+array_1d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
A = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])


In [ ]:
print(A + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
def categorize_rating(rating):
    "Categorize ratings into high or low."""
    if rating >= 4.0:
        return "High"
    else:
        return "Low"

In [ ]:
vectorised_func= np.vectorize(categorize_rating)

In [ ]:
vectorised_func([1,2,3,4,5,6,7])

array(['Low', 'Low', 'Low', 'High', 'High', 'High', 'High'], dtype='<U4')

In [ ]:
# Define a function to calculate the discounted cost
def discount_cost(cost):
    return cost * 0.9

In [ ]:
x=[100.0,200.0,300.0,400.0]

In [ ]:
vectorised_discounts= np.vectorize(discount_cost)

In [ ]:
vectorised_discounts(x)


array([ 90., 180., 270., 360.])

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5, 6,8,9,10])

In [ ]:
x= np.split(array_1d, 3)

In [ ]:
x[0]

array([1, 2, 3])

In [ ]:
y= np.split(array_1d, 4)

ValueError: array split does not result in an equal division

In [ ]:
#HW -- Explore how this splitting works in 2D , Row wise splitting, column wise splitting

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])


In [ ]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [ ]:
np.vstack([array1,array2] )

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack([array1,array2] )

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

In [ ]:
a

array([[1, 2]])

In [ ]:
b

array([[3, 4]])

In [ ]:
np.concatenate([a, b],axis=1)

array([[1, 2, 3, 4]])