In [10]:
print("Hello AI/ML People")

Hello AI/ML People


In [11]:
x = 3
y = 5
z=x+y

print(z)

8


In [12]:
a = 3
b= "prince"

c = a + b

print(c)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [13]:
a = "3"
b= "prince"

c = a + b

print(c)

3prince


In [14]:
#how to find the datatype

prince = 5
archana = "Hi"


In [15]:
type(prince)

int

In [16]:
type(archana)

str

In [17]:
students = [1,2,3,4,5,6] #list

In [18]:
students[-1]

6

In [19]:
students[0]

1

In [20]:
#can list only store similar datatype or just numbers
students_new= ['prince', 'Chandan', 1,2, 'a', 44.22, True]

In [21]:
students_new[1] #the index starts from 0

'Chandan'

In [22]:
#For doing numerical operations it is slow ---> Numpy

In [23]:
import numpy as np

In [24]:
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["800.0" ,"800.0", "800.0", "300.0", "600.0", "600.0", "600.0", "700.0" ,"550.0", "500.0"])

In [25]:
print(votes)

[ 775  787  918   88  166  286 2556  324  504  402]


In [26]:
print(costs)

['800.0' '800.0' '800.0' '300.0' '600.0' '600.0' '600.0' '700.0' '550.0'
 '500.0']


In [27]:
#multiply all votes by 2

votes * 2

array([1550, 1574, 1836,  176,  332,  572, 5112,  648, 1008,  804])

In [28]:
py_list = [1,2,3,4,5]

In [29]:
py_list*2 #doesn't work in normal python

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [30]:
votes.shape

(10,)

In [31]:
costs.shape

(10,)

In [32]:
votes.ndim

1

In [33]:
votes.size

10

In [34]:
np.array([
    votes, costs
])

array([['775', '787', '918', '88', '166', '286', '2556', '324', '504',
        '402'],
       ['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
        '700.0', '550.0', '500.0']], dtype='<U21')

In [35]:
array_new= np.array([
    votes, costs
]).T

In [36]:
array_new

array([['775', '800.0'],
       ['787', '800.0'],
       ['918', '800.0'],
       ['88', '300.0'],
       ['166', '600.0'],
       ['286', '600.0'],
       ['2556', '600.0'],
       ['324', '700.0'],
       ['504', '550.0'],
       ['402', '500.0']], dtype='<U21')

In [37]:
array_new.shape

(10, 2)

In [38]:
array_new.ndim

2

In [39]:
array_new.size

20

In [40]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [41]:
votes[-1]

np.int64(402)

In [42]:
votes[3]

np.int64(88)

In [43]:
votes[0:4]

array([775, 787, 918,  88])

In [44]:
votes[0:5]

array([775, 787, 918,  88, 166])

In [45]:
array_new

array([['775', '800.0'],
       ['787', '800.0'],
       ['918', '800.0'],
       ['88', '300.0'],
       ['166', '600.0'],
       ['286', '600.0'],
       ['2556', '600.0'],
       ['324', '700.0'],
       ['504', '550.0'],
       ['402', '500.0']], dtype='<U21')

In [46]:
#first 3 rows of this 2D array #i am printing all the columns
array_new[0:3]

array([['775', '800.0'],
       ['787', '800.0'],
       ['918', '800.0']], dtype='<U21')

In [47]:
array_new[0:3, 0:1] #more customizable

array([['775'],
       ['787'],
       ['918']], dtype='<U21')

In [48]:
array_new[0:1, 0:1]

array([['775']], dtype='<U21')

In [49]:
array_new[0:5,0:1]

array([['775'],
       ['787'],
       ['918'],
       ['88'],
       ['166']], dtype='<U21')

In [50]:
array_new[4:5,0:1]

array([['166']], dtype='<U21')

In [51]:
array_new.shape

(10, 2)

In [52]:
array_new[:,0]

array(['775', '787', '918', '88', '166', '286', '2556', '324', '504',
       '402'], dtype='<U21')

In [53]:
array_new[0:10,0]

array(['775', '787', '918', '88', '166', '286', '2556', '324', '504',
       '402'], dtype='<U21')

In [54]:
#shape (m,1) and shape (m,) - is it the same?
#I assumed the result is (items, dimensions)
#in numpy no